"""Initial migration.

Revision ID: 084fc2fe5ca5
Revises: 4ae6e4dda504
Create Date: 2022-08-24 19:02:09.283730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084fc2fe5ca5'
down_revision = '4ae6e4dda504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_icon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_icon_title', sa.String(length=180), nullable=False),
    sa.Column('about_icon_text', sa.String(length=220), nullable=False),
    sa.Column('about_icon_img', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('about_icon_text'),
    sa.UniqueConstraint('about_icon_title')
    )
    op.create_table('about_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_title', sa.String(length=180), nullable=False),
    sa.Column('about_text', sa.String(length=220), nullable=False),
    sa.Column('about_video', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('about_text'),
    sa.UniqueConstraint('about_title')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_title', sa.String(length=180), nullable=False),
    sa.Column('service_text', sa.String(length=220), nullable=False),
    sa.Column('service_img', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_text'),
    sa.UniqueConstraint('service_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('about_us')
    op.drop_table('about_icon')
    # ### end Alembic commands ###
