"""stat model create

Revision ID: 1e89fc81efb6
Revises: 1eb6a8400aea
Create Date: 2022-09-27 18:00:11.694387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e89fc81efb6'
down_revision = '1eb6a8400aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clients', sa.Integer(), nullable=True),
    sa.Column('projects', sa.Integer(), nullable=True),
    sa.Column('hours_of_support', sa.Integer(), nullable=True),
    sa.Column('workers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
