"""register

Revision ID: 1eb6a8400aea
Revises: 7c22b607c566
Create Date: 2022-09-26 21:57:26.785123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb6a8400aea'
down_revision = '7c22b607c566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
