"""Initial migration.

Revision ID: 377d635aa96a
Revises: 
Create Date: 2022-08-24 17:14:13.865711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377d635aa96a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nav_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navbar_name', sa.String(length=180), nullable=False),
    sa.Column('navbar_url', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('navbar_name'),
    sa.UniqueConstraint('navbar_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nav_bar')
    # ### end Alembic commands ###
