"""Initial migration.

Revision ID: 3b59aac49e73
Revises: 084fc2fe5ca5
Create Date: 2022-08-24 19:03:32.348523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b59aac49e73'
down_revision = '084fc2fe5ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'service_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_img', sa.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
