"""Initial migration.

Revision ID: 4ae6e4dda504
Revises: 377d635aa96a
Create Date: 2022-08-24 17:32:57.062521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae6e4dda504'
down_revision = '377d635aa96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport_title', sa.String(length=180), nullable=False),
    sa.Column('transport_text', sa.String(length=220), nullable=False),
    sa.Column('transport_img', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transport_text'),
    sa.UniqueConstraint('transport_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport')
    # ### end Alembic commands ###
