"""social media model

Revision ID: 5030e7a4e889
Revises: d47da7f97d3d
Create Date: 2022-09-28 20:26:52.127052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5030e7a4e889'
down_revision = 'd47da7f97d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('social_name', sa.String(length=180), nullable=True),
    sa.Column('social_icon', sa.String(length=120), nullable=True),
    sa.Column('social_url', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('about_us')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_us',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('about_title', sa.VARCHAR(length=180), nullable=False),
    sa.Column('about_text', sa.VARCHAR(length=220), nullable=True),
    sa.Column('about_video', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('about_title')
    )
    op.drop_table('social_media')
    # ### end Alembic commands ###
