"""empty message

Revision ID: 65acd6e4cb80
Revises: 6d0f4ac3ffc3
Create Date: 2022-11-05 17:28:27.771401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65acd6e4cb80'
down_revision = '6d0f4ac3ffc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faq_question', sa.String(length=220), nullable=True),
    sa.Column('faq_answer', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_title', sa.String(length=180), nullable=True),
    sa.Column('feature_img', sa.String(length=120), nullable=True),
    sa.Column('feature_text', sa.Text(), nullable=True),
    sa.Column('feature_orderimg', sa.String(length=80), nullable=True),
    sa.Column('feature_ordertext', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(length=220), nullable=True),
    sa.Column('message_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nav_bar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('navbar_name', sa.String(length=180), nullable=False),
    sa.Column('navbar_url', sa.String(length=180), nullable=False),
    sa.Column('navbar_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('navbar_name'),
    sa.UniqueConstraint('navbar_order'),
    sa.UniqueConstraint('navbar_url')
    )
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pricing_name', sa.String(length=180), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_title', sa.String(length=180), nullable=False),
    sa.Column('service_text', sa.Text(), nullable=True),
    sa.Column('service_img', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_title')
    )
    op.create_table('social_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('social_name', sa.String(length=180), nullable=True),
    sa.Column('social_icon', sa.String(length=120), nullable=True),
    sa.Column('social_url', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=220), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('employee_img', sa.String(length=220), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_social',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('social_name', sa.String(length=180), nullable=True),
    sa.Column('social_icon', sa.String(length=120), nullable=True),
    sa.Column('social_url', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('profession', sa.String(length=80), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('img', sa.String(length=80), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transport_title', sa.String(length=180), nullable=False),
    sa.Column('transport_text', sa.String(length=220), nullable=True),
    sa.Column('transport_img', sa.String(length=120), nullable=True),
    sa.Column('transport_url', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transport_title')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=80), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('user_info', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('pricing_incridents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pricing_incrident_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pricing_incrident_id'], ['pricing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_gallery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teamgallery_id', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['teamgallery_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_gallery')
    op.drop_table('pricing_incridents')
    op.drop_table('users')
    op.drop_table('transport')
    op.drop_table('testimonials')
    op.drop_table('team_social')
    op.drop_table('team')
    op.drop_table('stats')
    op.drop_table('social_media')
    op.drop_table('services')
    op.drop_table('pricing')
    op.drop_table('nav_bar')
    op.drop_table('messages')
    op.drop_table('feature')
    op.drop_table('faqs')
    # ### end Alembic commands ###
