"""user

Revision ID: 6d0f4ac3ffc3
Revises: b085b9878e9e
Create Date: 2022-10-21 08:39:03.572371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0f4ac3ffc3'
down_revision = 'b085b9878e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_authorized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_authorized')
    # ### end Alembic commands ###
