"""add model

Revision ID: 79e347b02fcf
Revises: 
Create Date: 2022-09-24 17:31:24.260350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e347b02fcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature', sa.Column('feature_orderimg', sa.String(length=80), nullable=True))
    op.add_column('feature', sa.Column('feature_ordertext', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature', 'feature_ordertext')
    op.drop_column('feature', 'feature_orderimg')
    # ### end Alembic commands ###
