"""pricing model add

Revision ID: 7e37729b2215
Revises: 028448d52e6f
Create Date: 2022-10-12 18:42:21.026756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e37729b2215'
down_revision = '028448d52e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pricing_name', sa.String(length=180), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('incridents', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('about_icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_icon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('about_icon_title', sa.VARCHAR(length=180), nullable=False),
    sa.Column('about_icon_text', sa.VARCHAR(length=220), nullable=True),
    sa.Column('about_icon_img', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('about_icon_title')
    )
    op.drop_table('pricing')
    # ### end Alembic commands ###
