"""Initial migration.

Revision ID: 90010e405d82
Revises: 3b59aac49e73
Create Date: 2022-08-24 19:04:06.098390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90010e405d82'
down_revision = '3b59aac49e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_img', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'service_img')
    # ### end Alembic commands ###
