"""update

Revision ID: 9e86edb927f9
Revises: 946e7828f620
Create Date: 2022-09-04 13:28:49.720791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e86edb927f9'
down_revision = '946e7828f620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nav_bar', sa.Column('navbar_order', sa.Integer(), nullable=True))
    op.add_column('nav_bar', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'nav_bar', ['navbar_order'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nav_bar', type_='unique')
    op.drop_column('nav_bar', 'is_active')
    op.drop_column('nav_bar', 'navbar_order')
    # ### end Alembic commands ###
