"""stat model edit

Revision ID: d47da7f97d3d
Revises: 1e89fc81efb6
Create Date: 2022-09-27 18:46:18.719102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47da7f97d3d'
down_revision = '1e89fc81efb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('name', sa.String(length=220), nullable=True))
    op.add_column('stats', sa.Column('value', sa.Integer(), nullable=True))
    op.drop_column('stats', 'projects')
    op.drop_column('stats', 'hours_of_support')
    op.drop_column('stats', 'clients')
    op.drop_column('stats', 'workers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('workers', sa.INTEGER(), nullable=True))
    op.add_column('stats', sa.Column('clients', sa.INTEGER(), nullable=True))
    op.add_column('stats', sa.Column('hours_of_support', sa.INTEGER(), nullable=True))
    op.add_column('stats', sa.Column('projects', sa.INTEGER(), nullable=True))
    op.drop_column('stats', 'value')
    op.drop_column('stats', 'name')
    # ### end Alembic commands ###
